name: docker-wp-nginx-php-mariadb
services:
  nginx:
    build: ./nginx
    image: wp_nginx:latest
    container_name: wp_nginx
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - php
    volumes:
      # Mount the named volume as read-only for Nginx
      - app_code:/var/www/html:ro

  php:
    build: ./php
    image: wp_php:latest
    container_name: wp_php
    depends_on:
      - db
    volumes:
      # Mount the named volume as read-write for PHP
      - app_code:/var/www/html:rw

  db:
    image: mariadb:latest
    container_name: wp_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db_data:/var/lib/mysql
    command: --bind-address=${DB_BIND_ADDRESS}

  adminer:
    image: adminer:latest
    container_name: wp_adminer
    depends_on:
      - db
    ports:
      - ${ADMINER_PORT}:8080
    environment:
      ADMINER_DEFAULT_SERVER: db

volumes:
  db_data:
  app_code:
