name: Docker-Image-CI

on:
  push:
    branches:
      - '**'  # Matches all branches
  pull_request:
    branches:
      - main # Trigger on pull requests targeting the main branch

jobs:
  build-and-run:
    runs-on: ubuntu-latest # Specify the runner environment
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Checkout the repository content

      - name: Build the Docker image
        run: docker compose up -d --build
